/* cert.h -- JSONL certificate stream writer and stateless re-check reader.
 *
 * One JSON line per leaf:
 *   {"box":[[lo,hi],[lo,hi],[lo,hi],[lo,hi]],
 *    "status":"discarded|certified|survivor",
 *    "item":<int, -1 if none>,
 *    "encl":[flo,fhi],
 *    "prec":<int>}
 *
 * The verifier re-derives each leaf's claim from (box, status, item) alone,
 * ignoring the recorded enclosure, optionally at a different precision.  It
 * also checks that the leaves form the complete dyadic partition of the root
 * box generated by the splitter, so truncated or overlapping certificates fail.
 */
#ifndef TRAP_CERT_H
#define TRAP_CERT_H

#include <stdio.h>
#include "search.h"

/* Writer context: pass as the leaf_fn ctx. */
typedef struct { FILE *fp; } cert_writer;

/* leaf_fn compatible callback that writes one JSONL line. */
void cert_write_leaf(void *ctx, const double lo[4], const double hi[4],
                     int status, int item, const arb_t encl, slong prec);

/* Re-check a complete certificate file statelessly.
 *   theta, form, half : the claimed run parameters;
 *   prec              : precision to re-verify at (may differ from the file);
 * Returns 0 if every leaf's claim holds, else the number of failures.
 * Prints a summary to stdout. */
int cert_verify(const char *path, double theta, enclosure_form form,
                int half, slong prec);

/* Load the survivor boxes of a certificate into freshly-malloc'd arrays
 * (*lo)[4] / (*hi)[4]; returns their count (0 on error; caller frees). */
size_t cert_load_survivors(const char *path, double (**lo)[4], double (**hi)[4]);

#endif /* TRAP_CERT_H */
