/* cert.h -- JSONL certificate stream writer and stateless re-check reader.
 *
 * The first JSON line is metadata:
 *   {"type":"meta","schema":2,"theta":<double>,"form":"natural|centered",
 *    "half":true|false, ...}
 *
 * Subsequent JSON lines contain one leaf each:
 *   {"box":[[lo,hi],[lo,hi],[lo,hi],[lo,hi]],
 *    "status":"discarded|certified|flat_area|nonoptimal|survivor",
 *    "item":<int, -1 if none>,
 *    "encl":[flo,fhi],
 *    "prec":<int>}
 *
 * The verifier re-derives each leaf's claim from (box, status, item) alone,
 * ignoring the recorded enclosure, optionally at a different precision.  It
 * also checks that the leaves form the complete dyadic partition of the root
 * box generated by the splitter, so truncated or overlapping certificates fail.
 */
#ifndef TRAP_CERT_H
#define TRAP_CERT_H

#include <stdio.h>
#include "search.h"

/* Writer context: pass as the leaf_fn ctx. */
typedef struct { FILE *fp; } cert_writer;

/* Write the self-describing certificate metadata line. */
void cert_write_meta(FILE *fp, const search_params *p);

/* leaf_fn compatible callback that writes one JSONL line. */
void cert_write_leaf(void *ctx, const double lo[4], const double hi[4],
                     int status, int item, const arb_t encl, slong prec);

/* Re-check a complete certificate file statelessly.
 *   theta/form/half, when *_set is true, are checked against the file metadata;
 *   prec              : precision to re-verify at (may differ from the file);
 * Returns 0 if every leaf's claim holds, else the number of failures.
 * Prints a summary to stdout. */
int cert_verify(const char *path, double theta, int theta_set,
                enclosure_form form, int form_set,
                int half, int half_set, slong prec);

/* Load the survivor boxes of a certificate into freshly-malloc'd arrays
 * (*lo)[4] / (*hi)[4]; returns their count (0 on error; caller frees). */
size_t cert_load_survivors(const char *path, double (**lo)[4], double (**hi)[4]);

/* Assemble a full-domain certificate from a base certificate and zero or more
 * refinement certificates.  Each refinement must tile exactly the survivor
 * boxes remaining from the previous stage. */
int cert_assemble(const char **paths, size_t npaths, const char *out_path);

#endif /* TRAP_CERT_H */
