function write_certificate_leaf(writer, leaf)
%WRITE_CERTIFICATE_LEAF Write one round-trip-safe JSONL leaf record.

if finite_interval(leaf.enclosure)
    witness = sprintf('[%.17g,%.17g]', ...
                      inf(leaf.enclosure), sup(leaf.enclosure));
else
    witness = 'null';
end
fprintf(writer.fileId, ...
    ['{"box":[[%.17g,%.17g],[%.17g,%.17g],[%.17g,%.17g],' ...
     '[%.17g,%.17g]],"status":"%s","item":%d,"seed":%d,' ...
     '"path":"%s","witness":%s}\n'], ...
    leaf.lo(1), leaf.hi(1), leaf.lo(2), leaf.hi(2), ...
    leaf.lo(3), leaf.hi(3), leaf.lo(4), leaf.hi(4), ...
    leaf.status, leaf.item, leaf.seed, leaf.path, witness);
end

function yes = finite_interval(value)
yes = ~any(isnan(inf(value))) && ~any(isnan(sup(value))) && ...
      all(isfinite(inf(value))) && all(isfinite(sup(value)));
end
